version: '3.8'
services:
  user_information_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: user_information_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=contrasenasegura
      - MYSQL_DATABASE=USER_INFORMATION
      - MYSQL_USER=grupo1b
      - MYSQL_PASSWORD=cristianoronaldo
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    expose:
      - 3306

  user_info_ms:
    container_name: user_info_ms
    build: .
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - MYSQL_DB=USER_INFORMATION
      - MYSQL_USER=grupo1b
      - MYSQL_PASSWORD=cristianoronaldo
      - MYSQL_HOST=user_information_db
      - MYSQL_PORT=3306
    depends_on:
      - user_information_db

